name: peopleapp_flutter
description: "People Token App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3"
  flutter: ">=3.16.6"

dependencies:
  bs58: ^1.0.2
  cupertino_icons: ^1.0.8
  eth_sig_util: ^0.0.9
  flutter:
    sdk: flutter
  intl: ^0.20.1
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.2
  qr_flutter: ^4.1.0
  reown_appkit: ^1.4.2+1
  toastification: ^2.3.0
  dio: ^5.0.0
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  carousel_slider: ^5.0.0
  fl_chart: ^0.65.0
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  google_sign_in: ^6.2.2
  flutter_launcher_icons: ^0.14.3
  flutter_secure_storage: ^9.0.0
  solana: ^0.31.2
  go_router: ^14.8.1
  image_picker: ^1.0.7
  get_it: ^8.0.3
  fluttertoast: ^8.0.8
  pinput:
  lottie:
  sign_in_with_apple: ^6.1.4

dependency_overrides:
  coinbase_wallet_sdk:
    git:
      url: https://github.com/WalletConnect/wallet-mobile-sdk.git
      ref: "2.0"
      path: flutter

dev_dependencies:
  build_runner: ^2.4.13
  dependency_validator: ^4.1.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/people_logo.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  fonts:
    - family: sonoma
      fonts:
        - asset: assets/fonts/BRSonoma-regular.otf

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/logo.png
    - assets/default_user.png