// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb8pAM0XDV-lVSXiWW8vrbrkCToi1UfQU',
    appId: '1:224874451784:android:8d3e91af3f42ed6102997d',
    messagingSenderId: '224874451784',
    projectId: 'peopleapp-3a8ae',
    storageBucket: 'peopleapp-3a8ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1bsjSMO70ITAhxozFIRDSREf9ol4WOLo',
    appId: '1:224874451784:ios:6a8805f4215cc52302997d',
    messagingSenderId: '224874451784',
    projectId: 'peopleapp-3a8ae',
    storageBucket: 'peopleapp-3a8ae.firebasestorage.app',
    androidClientId: '224874451784-322qr7ruqg8n7b7v7va6uagi0e3huprr.apps.googleusercontent.com',
    iosClientId: '224874451784-uqi5c4s0u1t5qsf34icmc8fh65rt2btv.apps.googleusercontent.com',
    iosBundleId: 'com.peopleapp.ios',
  );

}